import test from 'node:test';import assert from 'node:assert/strict';
// @ts-expect-error Plain ESM server module is also used directly by Vercel.
import {validateContact,createToken,validToken,createLimiter,createHandler} from '../server/contact.mjs';
const valid={name:'Visiteur Test',email:'visiteur@example.com',subject:'Une question sur Speakora',message:'Un message suffisamment long pour tester le formulaire.',website:''};
const env={SMTP_HOST:'smtp.example.com',SMTP_PORT:'465',SMTP_SECURE:'true',SMTP_USER:'sender@example.com',SMTP_PASSWORD:'test-only',SMTP_FROM:'sender@example.com',CONTACT_RECIPIENT:'owner@example.com',CONTACT_FORM_SECRET:'test-secret-not-production'};
const request=(body:unknown,extra={})=>({method:'POST',headers:{origin:'https://speakora.morashawiri.com','content-type':'application/json','x-vercel-forwarded-for':'192.0.2.1'},body,...extra});
function response(){return {code:0,data:{} as any,headers:{} as Record<string,string>,setHeader(k:string,v:string){this.headers[k]=v;},status(n:number){this.code=n;return this;},json(data:unknown){this.data=data;return this;}};}
test('contact validates lengths, exact subjects and prevents header injection',()=>{assert.ok(validateContact(valid));for(const change of [{name:'X'},{name:'Name\r\nBcc: bad@example.com'},{email:'bad@example.com\nBcc: bad@example.com'},{subject:'arbitrary'},{message:'short'},{message:'a'.repeat(5001)}])assert.equal(validateContact({...valid,...change}),null);});
test('contact token rejects tampering, expiration and future dates',()=>{const token=createToken('key',1000);assert.equal(validToken(token,'key',2000),true);assert.equal(validToken(token,'other',2000),false);assert.equal(validToken(token,'key',3601001),false);assert.equal(validToken(token,'key',999),false);assert.equal(validToken(token+'a','key',2000),false);});
test('throttle expires and isolates IPs',()=>{const limit=createLimiter();assert.ok(limit('a',0));assert.ok(limit('a',1));assert.ok(limit('a',2));assert.equal(limit('a',3),false);assert.ok(limit('b',3));assert.ok(limit('a',600001));});
test('handler sends only to configured recipient and rejects token reuse',async()=>{let sent:any;const handler=createHandler({env,send:async(m:unknown)=>{sent=m;return {accepted:['owner@example.com']};}});const body={...valid,token:createToken(env.CONTACT_FORM_SECRET),to:'attacker@example.com'};const res=response();await handler(request(body),res);assert.equal(res.code,200);assert.equal(sent.to,env.CONTACT_RECIPIENT);assert.equal(sent.from,env.SMTP_FROM);assert.equal(sent.replyTo.address,valid.email);assert.ok(sent.text.includes(valid.message));const duplicate=response();await handler(request(body),duplicate);assert.equal(duplicate.code,409);});
test('handler rejects cross-origin, missing token and honeypot without email',async()=>{let calls=0;const handler=createHandler({env,send:()=>{calls++;}});for(const req of [request(valid),request({...valid,token:createToken(env.CONTACT_FORM_SECRET),website:'bot'}),request({...valid,token:createToken(env.CONTACT_FORM_SECRET)},{headers:{origin:'https://other.example','content-type':'application/json'}})]){const res=response();await handler(req,res);assert.ok(res.code>=400);}assert.equal(calls,0);});
test('SMTP failure is not reported as success and allows retry',async()=>{let calls=0;const handler=createHandler({env,send:async()=>{calls++;if(calls===1)throw new Error('secret server detail');return {accepted:['owner@example.com']};}});const req=request({...valid,token:createToken(env.CONTACT_FORM_SECRET)});const failed=response();await handler(req,failed);assert.equal(failed.code,502);assert.ok(!JSON.stringify(failed.data).includes('secret'));const retry=response();await handler(req,retry);assert.equal(retry.code,200);});
