import test from 'node:test';import assert from 'node:assert/strict';import {createServer,type Socket} from 'node:net';import nodemailer from 'nodemailer';
// @ts-expect-error Real server handler, exercised through real TCP/SMTP on loopback.
import {createHandler,createToken} from '../server/contact.mjs';
async function receiver(codes:number[]){
 const sockets=new Set<Socket>();let deliveries=0;const messages:string[]=[];
 const server=createServer(socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.write('220 local-test.example ESMTP\r\n');let buffer='',data=false,content='';
 socket.on('data',chunk=>{buffer+=chunk.toString();while(buffer.includes('\r\n')){const at=buffer.indexOf('\r\n');const line=buffer.slice(0,at);buffer=buffer.slice(at+2);if(data){if(line==='.'){data=false;messages.push(content);content='';const code=codes[deliveries++]||250;socket.write(code===250?'250 2.0.0 Accepted locally for test\r\n':`${code} 5.7.1 Deliberate test rejection\r\n`);}else content+=line+'\n';continue;}if(/^EHLO|^HELO/.test(line))socket.write('250-local-test.example\r\n250 8BITMIME\r\n');else if(/^MAIL FROM:|^RCPT TO:|^RSET/.test(line))socket.write('250 2.1.0 OK\r\n');else if(line==='DATA'){data=true;socket.write('354 End with dot\r\n');}else if(line==='QUIT'){socket.end('221 Bye\r\n');}else socket.write('500 Unsupported in test receiver\r\n');}});
 });
 await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port;
 // TLS is intentionally disabled only for this isolated local test receiver. Production requires TLS.
 const transport=nodemailer.createTransport({host:'127.0.0.1',port,secure:false,ignoreTLS:true,connectionTimeout:2000,socketTimeout:2000});
 return {transport,messages,get deliveries(){return deliveries;},close:()=>new Promise<void>(resolve=>{for(const socket of sockets)socket.destroy();server.close(()=>resolve());})};
}
const env={SMTP_HOST:'test-only',SMTP_PORT:'465',SMTP_SECURE:'true',SMTP_USER:'test',SMTP_PASSWORD:'test-only',SMTP_FROM:'sender@example.com',CONTACT_RECIPIENT:'owner@example.com',CONTACT_FORM_SECRET:'local-test-only'};
const contact={name:'Test local',email:'visitor@example.com',subject:'Une idée ou un retour',message:'Test local sans envoi de message sur Internet.',website:''};
const req=()=>({method:'POST',headers:{origin:'https://speakora.morashawiri.com','content-type':'application/json'},body:{...contact,token:createToken(env.CONTACT_FORM_SECRET)}});
const res=()=>({code:0,data:{} as any,setHeader(){},status(code:number){this.code=code;return this;},json(data:any){this.data=data;return this;}});
test('real SMTP 550 rejection results in HTTP 502 and no confirmation',async t=>{const smtp=await receiver([550]);t.after(smtp.close);let code:number|undefined;const handler=createHandler({env,send:async(m:any)=>{try{return await smtp.transport.sendMail(m);}catch(e:any){code=e.responseCode;throw e;}}});const response=res();await handler(req(),response);assert.equal(code,550);assert.equal(response.code,502);assert.equal(smtp.deliveries,1);assert.ok(!response.data.confirmationEmailSent);});
test('real SMTP accepts admin then rejects confirmation without false full success',async t=>{const smtp=await receiver([250,550]);t.after(smtp.close);const handler=createHandler({env,send:(m:any)=>smtp.transport.sendMail(m)});const response=res();await handler(req(),response);assert.equal(response.code,200);assert.equal(response.data.confirmationEmailSent,false);assert.equal(smtp.deliveries,2);assert.ok(smtp.messages[0].includes('To: owner@example.com'));assert.ok(smtp.messages[1].includes('To: visitor@example.com'));});
test('real SMTP receives two multipart messages after one successful submission',async t=>{const smtp=await receiver([250,250]);t.after(smtp.close);const handler=createHandler({env,send:(m:any)=>smtp.transport.sendMail(m)});const response=res();await handler(req(),response);assert.equal(response.code,200);assert.equal(response.data.confirmationEmailSent,true);assert.equal(smtp.deliveries,2);for(const message of smtp.messages){assert.ok(message.includes('multipart/alternative'));assert.ok(message.includes('text/html'));assert.ok(message.includes('text/plain'));}});
