import fs from 'node:fs';import {chromium} from '@playwright/test';
const dest='../04 Captures/Affiches campagne';fs.mkdirSync(dest,{recursive:true});
const data=(file,mime)=>`data:${mime};base64,${fs.readFileSync(file).toString('base64')}`;
const logo=data('public/brand/logo.webp','image/webp');const screen=data('../04 Captures/Sur Mobile/03b-exercice-ecran.png','image/png');const font=data('node_modules/@fontsource-variable/manrope/files/manrope-latin-wght-normal.woff2','font/woff2');
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1080,height:1080},deviceScaleFactor:1});
for(const [name,kicker,title,description,pill] of [
 ['01-apprendre','VOTRE PROCHAIN CHAPITRE','L’anglais ouvre<br>des portes.','De petites leçons.<br>De vrais moments de déclic.','5 niveaux · 82 exercices'],
 ['02-hors-connexion','VOTRE ANGLAIS VOUS SUIT','Pas de réseau ?<br>Gardez l’élan.','Vos leçons vous accompagnent,<br>même hors connexion.*','Mobile · PWA · Progression locale']
]){
 const html=`<!doctype html><html lang="fr"><meta charset="utf-8"><style>@font-face{font-family:Manrope;src:url('${font}');font-weight:200 800}*{box-sizing:border-box}body{margin:0;width:1080px;height:1080px;overflow:hidden;font-family:Manrope,Arial;background:#f5f7fb;color:#111827}.poster{padding:65px;height:100%;position:relative;background:radial-gradient(ellipse at 90% 55%,#dcccff 0,transparent 65%)}.logo{width:295px}.kicker{font-size:17px;color:#6d5cff;letter-spacing:3px;font-weight:800;margin-top:64px}.title{font-size:69px;font-weight:800;line-height:1.08;letter-spacing:-4px;position:relative;z-index:3;max-width:600px;margin-top:22px}.description{font-size:26px;color:#65627a;line-height:1.6;margin-top:30px;position:relative;z-index:3;max-width:500px}.pill{display:inline-block;border:1px solid #d6c8f2;color:#665088;border-radius:40px;padding:12px 20px;font-size:19px;margin-top:25px;background:#fff9}.phone{position:absolute;right:42px;top:330px;width:320px;height:590px;background:white;border:9px solid #fff;border-radius:32px;overflow:hidden;box-shadow:0 30px 65px #513a7c30;transform:rotate(7deg)}.phone img{width:100%;display:block}.cta{position:absolute;left:65px;bottom:190px;font-size:24px;font-weight:750;border-radius:15px;color:white;background:linear-gradient(100deg,#6d5cff,#a855f7);padding:20px 28px;box-shadow:0 5px 0 #5946c8}.footer{position:absolute;bottom:46px;left:65px;right:65px;border-top:1px solid #d9d1e7;padding-top:25px;display:flex;justify-content:space-between;align-items:end}.footer b{font-size:21px;display:block}.footer span{font-size:16px;color:#747080;display:block;margin-top:6px}.footer small{font-size:14px;color:#716981}.footnote{position:absolute;left:65px;bottom:145px;font-size:12px;color:#746d83;width:470px}</style><div class="poster"><img class="logo" src="${logo}" alt="Speakora"><div class="kicker">${kicker}</div><div class="title">${title}</div><div class="description">${description}</div><div class="pill">${pill}</div><div class="phone"><img src="${screen}" alt="Capture réelle d’un exercice Speakora"></div><div class="cta">Commencez gratuitement</div>${name.includes('connexion')?'<div class="footnote">* Après un premier chargement en ligne. Audio selon les voix de l’appareil.</div>':''}<div class="footer"><div><b>speakora.morashawiri.com</b><span>Apprenez. Pratiquez. Progressez.</span></div><small>Par MORA Shawiri</small></div></div></html>`;
 fs.writeFileSync(`${dest}/${name}.html`,html);await page.setContent(html);await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`${dest}/${name}.png`});
}
await browser.close();console.log('Two 1080 × 1080 campaign posters created from official logo and real production screenshot.');
