import fs from 'node:fs';
const explanations={
 a1:[
 ['Hello est la salutation courante pour dire bonjour.','Goodbye signifie au revoir. Please veut dire s’il vous plaît.','Avec le sujet I, le verbe be devient am : I am John.','Nice to meet you signifie « Enchanté de faire votre connaissance ».','En anglais, le sujet précède le verbe : I + am + fine.'],
 ['Red signifie rouge ; blue, bleu ; green, vert ; yellow, jaune.','Seven correspond au nombre sept.','Blue signifie bleu. Après is, on décrit ici la couleur du ciel.','Three signifie trois. Attention à tree, qui signifie arbre.','La phrase indique trois pommes vertes : three green apples.','On suit l’ordre sujet + verbe + adjectif : The grass + is + green.'],
 ['Mother signifie mère. My mother signifie ma mère.','Brother signifie frère. Sister signifie sœur.','Avec she, on utilise is : She is my sister.','This is my father signifie « Voici mon père ».','My brother est le sujet, is le verbe et tall l’adjectif : grand.']
 ],
 a2:[
 ['To wake up signifie se réveiller. La particule up fait partie du verbe.','Au présent simple, go devient goes avec he, she et it.','Usually signifie généralement et se place avant le verbe have. Breakfast est le petit-déjeuner.','Go to bed signifie aller se coucher ; ten o’clock indique dix heures.','Avec she, work prend un -s. Every day signifie tous les jours.'],
 ['I would like est une demande polie : je voudrais.','Après can, on utilise le verbe sans to et sans conjugaison : have.','The bill désigne l’addition. Please rend la demande polie.','A table for two signifie une table pour deux personnes.','Would like est suivi ici du groupe nominal some water : de l’eau.'],
 ['Last year situe l’action dans le passé. Le prétérit irrégulier de go est went.','Yesterday appelle le prétérit : watched, formé avec -ed.','Pour cette action passée terminée, on utilise played, le prétérit de play.','Last week signifie la semaine dernière. Visited est le prétérit de visit.','Après didn’t, le verbe reste à la base verbale : come, et non came.','Le prétérit irrégulier de see est saw. A dog signifie un chien.']
 ],
 b1:[
 ['Le present perfect se forme avec have + participe passé. Avec I, on emploie have.','Since 2010 relie un point de départ passé à une situation toujours actuelle : has lived.','La question au present perfect place Have avant le sujet you.','For accompagne une durée, ici five years. Since accompagne un point de départ.','Just indique que l’action vient de se terminer : have just finished.','Know devient known au participe passé. For years indique une durée jusqu’au présent.'],
 ['Give up signifie abandonner ou renoncer.','Look for signifie chercher. Look after signifie s’occuper de.','Turn on signifie allumer. Turn off signifie éteindre.','Look after signifie prendre soin de quelqu’un ou de quelque chose.','Don’t give up on your dreams signifie « N’abandonnez pas vos rêves ».','Take after signifie ressembler à un membre de sa famille. Avec she : takes after.'],
 ['Will + verbe exprime ici une promesse spontanée : I will help you.','Be going to + verbe exprime une intention : are going to travel.','Les nuages constituent un indice visible : on utilise is going to rain.','It’s going to rain tomorrow signifie « Il va pleuvoir demain ».','Will est suivi de la base verbale arrive. Next week signifie la semaine prochaine.']
 ],
 b2:[
 ['Dans une hypothèse irréelle, If I were rich est la forme standard, suivie de would.','Une hypothèse irréalisée dans le passé utilise if + had studied, puis would have passed.','Le second conditionnel utilise le prétérit après if : if I had your number.','Pour une condition future possible : if + présent, puis will + verbe.','Unless introduit une exception : à moins que, sauf si.','If I were you signifie à ta place ; I would apply signifie je postulerais.'],
 ['La voix passive au passé se forme avec was + participe passé : was made.','Au present perfect passif : has been + participe passé, ici sent.','Au présent passif : is + spoken, participe passé de speak.','Was built est le passif au prétérit de build. L’année entendue est 1900.','The window subit l’action : was + broken, participe passé de break.'],
 ['It’s raining cats and dogs est une expression qui signifie qu’il pleut très fort.','Break a leg! est une façon idiomatique de souhaiter bonne chance, notamment avant une représentation.','Hit the sack signifie aller se coucher.','A piece of cake décrit quelque chose de très facile.','Let’s call it a day propose d’arrêter le travail ou l’activité pour aujourd’hui.']
 ],
 c1:[
 ['Meticulous décrit une personne extrêmement attentive aux détails.','To undermine signifie saper ou affaiblir progressivement, notamment une autorité ou un argument.','Lucid signifie clair et facile à comprendre. Les autres adjectifs ne conviennent pas ici.','Thorough signifie complet et approfondi.','Corroborate signifie confirmer ou appuyer par des éléments concordants.','Was deemed signifie a été jugé ; unfeasible signifie irréalisable.'],
 ['Rarely en tête de phrase entraîne une inversion : have I seen, et non I have seen.','Après it’s high time, on utilise le prétérit pour une action qui devrait déjà se produire : we left.','Had I known remplace if I had known. La conséquence passée est would have come.','Not only en tête de proposition entraîne l’inversion : did she win.','Little en tête de phrase entraîne l’inversion did he know ; le verbe reste à la base verbale après did.'],
 ['To beat around the bush signifie éviter d’aborder directement le sujet.','The elephant in the room désigne un problème évident que tout le monde évite d’évoquer.','Over the moon signifie extrêmement heureux ou ravi.','Doesn’t hold water signifie qu’un argument ne résiste pas à l’examen.','A blessing in disguise est un événement d’abord négatif qui se révèle finalement bénéfique.','It’s a blessing in disguise signifie que ce qui semblait être un problème se révèle une chance.']
 ]};
for(const [level,groups] of Object.entries(explanations)){const file=`src/data/${level}.json`;const data=JSON.parse(fs.readFileSync(file,'utf8'));data.lessons.forEach((l,i)=>l.exercises.forEach((e,j)=>{if(!groups[i][j])throw new Error('Missing explanation');e.explanation=groups[i][j];}));fs.writeFileSync(file,JSON.stringify(data,null,2)+'\n');}
